= Syncronizing two Tables on different servers using SqlBulkCopy
:source-highlighter: hightlightjs
:hp-tags: Sql, SqlBulkCopy, C#

I came across an intresting issue last week. +
We had a working code that syncronized local table with from remote one.

The concept of the code was simple: +
Since we needed to update existing rows and not only insert, we have a 'row_version' column that is uniq through the db and controlled by the remote db (the reference db). +
The remote will only send the deltas and on the local machine we iterate over all received records, check for each one if it exists and require update or it's a new record and should be inserted.

This worked well at the begining when we had 10-100 rows that were changed. +
But then, we had  syncronization of 100,000 rows. +
*This took 40 Minutes.*

.The old code
[source, C#]
fdfsf
fdsfdsf
fdsfsd

==== The new concept

I understood that I have to load the rows into the db as fast as possible and this can be acheived using BCP.
So, using SqlBulkCopy I loaded all rows into a temp table. + 
This is done by spliting the table into smaller chunks and parallel load them with BCP. +
The update/insert done using 3 queries:

. Add a column to the temp table and mark all records that exists on the real table.
. Update query
. Insert query

*The total runtime is now reduced to 40 Seconds!!*

.The new code - Load to temp table with BCP.
[source, C#]
using (SqlConnection conn = this.GetNewOpenedConnection())
{
  string tempTable = string.Format("T_{0}", dataTable.TableName);
  SqlCommand command = conn.CreateCommand();
  command.CommandText = string.Format(@"IF (NOT EXISTS (SELECT 1 
  			FROM INFORMATION_SCHEMA.TABLES 
  			WHERE TABLE_NAME = '{0}')) 
  			BEGIN 
  			select * into {0} from {1} where 1=2 
  			END", tempTable, dataTable.TableName); 
  command.ExecuteNonQuery();
  using (SqlBulkCopy copy = new SqlBulkCopy(conn))
  {
  	copy.DestinationTableName = tempTable;
  	copy.WriteToServer(dataTable);
  }
}

.The new code - Update/Insert from Temp table
[source, C#]
public void FinishFastCopy(string tableName)
{
   string TempTableName = string.Format("T_{0}", tableName);
   using (var conn = this.GetNewOpenedConnection())
   {
      var command = conn.CreateCommand();
      command.CommandText = string.Format(@"SELECT count(1)
      				FROM INFORMATION_SCHEMA.TABLES 
                                WHERE TABLE_NAME = '{0}'", TempTableName);
      if ((int)command.ExecuteScalar() != 1) return;
      command.CommandText = string.Format("select * from {0} where 1=2", TempTableName);
      List<string> columnsName;
      using (var sqlDataReader = command.ExecuteReader())
      {
         columnsName = sqlDataReader.GetSchemaTable().Rows.Cast<DataRow>().Where(row => row["ColumnName"].ToString() != "AUTOID").Select(row => row["ColumnName"].ToString()).ToList();
      }
      command.CommandText = string.Format("ALTER TABLE {0} add for_update bit", TempTableName);
      command.ExecuteNonQuery();
      command.CommandText = string.Format("update {0}  set for_update=1 where EXISTS (select 1 from {1} h where h.GUID = {0}.GUID)", TempTableName, tableName);
      command.ExecuteNonQuery();
      var commaSeperateColumns = string.Join(",", columnsName);    
      command.CommandText = string.Format(@"insert into {0} ({1}) select {1} from {2} as t where t.for_update is null", tableName, commaSeperateColumns, TempTableName);
      command.ExecuteNonQuery();
      var setCol = columnsName.Select(s => string.Format("{0}=t.{0}", s));
      var commaSeparatedSetCol = string.Join(",", setCol);
      command.CommandText = string.Format("update {0} SET {1} FROM {0} inner join {2} as t ON {0}.GUID=t.GUID where t.for_update=1", tableName,commaSeparatedSetCol,TempTableName);
      command.ExecuteNonQuery();
      command.CommandText = string.Format("DROP TABLE {0}", TempTableName);
      command.ExecuteNonQuery();
   }
}